### PR TITLE
#468

### PR DESCRIPTION
**Pull request by anandrgitnirman**
added a project ID for mainnet

### CODE REVIEW

**Comment by arturgontijo** [comment]
Can we get rid of the `"ethereum_json_rpc_endpoint":`?
Once we have set the `"blockchain_network_selected": "main",`.

**Comment by arturgontijo** [comment]
Let's add the Infura Key to all the networks (`kovan` and `rinkeby`) too.

**Comment by anandrgitnirman** [comment]
> Can we get rid of the `"ethereum_json_rpc_endpoint":`?
> Once we have set the `"blockchain_network_selected": "main",`.

incase a user want to use his own project ID, good to give an option, 
blockchain_network_selected is mandtory ,we cant get rid of this

**Comment by arturgontijo** [comment]
> incase a user want to use his own project ID, good to give an option,

Ok, but if a user sets `"blockchain_network_selected": "main",` and doesn't set `ethereum_json_rpc_endpoint`, the Daemon will work?

I'm trying to reduce the complexity (and points of failures) of the basic settings. =)

**Comment by anandrgitnirman** [comment]
> > incase a user want to use his own project ID, good to give an option,
> 
> Ok, but if a user sets `"blockchain_network_selected": "main",` and doesn't set `ethereum_json_rpc_endpoint`, the Daemon will work?
> 
> I'm trying to reduce the complexity (and points of failures) of the basic settings. =)

Yes, Daemon will work :) , this is tested if "blockchain_network_selected": "main", and doesn't set ethereum_json_rpc_endpoint

**Pull request merged**
