### PR TITLE
Issue #199  Behind NAT support 

### PR DESCRIPTION
**Pull request by anandrgitnirman**
Issue #199 

Get away from the Daemon End Point
Introduce group name to help with payments
Define the port number that the Daemon should listen to .

The issue with having a daemon end point was that it was forcing the endpoint defined to be exactly the same as what has been defined in the metadata ( this may not always be true as the daemon could run in a private network behind the NAT)
What has been defined in the meta data is for public access, how daemon runs in its private network or container should be agnostic to this public end point

### CODE REVIEW

**Comment by anandrgitnirman** [comment]
@vsbogd @raamb @astroseger 
Request your review on this change

**Comment by astroseger** [comment]
I propose to make ```daemon_group_name``` optional (with default = "default_group").

**Comment by anandrgitnirman** [comment]
hi @astroseger , corrected this in the Readme , code wise we have the daemon group as default_group

**Comment by ferrouswheel** [comment]
Nice!

One thing is that this seems renames the daemon end point config key. While, I can see a reason to do it... this will require everyone to change their config and for us to update our documentation. Created an issue on the dev-portal for this.

**Comment by astroseger** [comment]
It seems the only one problem is that now ```http://``` prefix is now allowed for daemon_end_point

**Comment by ferrouswheel** [comment]
@astroseger Ah yeah. I just saw the change to the documentation and assumed it had changed... but it's the same, the documentation was just being fixed. So ignore me haha :-)

**Pull request merged**
