### PR TITLE
test coverage badge

### PR DESCRIPTION
**Pull request by prashantramangupta**
resolves issue #264

### CODE REVIEW

**Comment by vsbogd** [comment]
What about hiding failed tests, is this problem resolved?

**Comment by raamb** [comment]
@vsbogd yes that's resolved. Removing the echo fixed that. There was another issue with the script running multiple times per folder which would cause the metrics test to fail (metrics test uses mockable which imposes a fair use policy. So when the tests were run multiple times there would be sporadic failures when mockable throttled). The issue of tests running multiple times has also been fixed now.

@prashantramangupta please add any details I might have missed out

**Comment by prashantramangupta** [comment]
Apart from this, we enabled `Pass secrets to builds from forked pull requests` in circleci Advance Settings.

**Comment by vsbogd** [comment]
Thanks @raamb , @prashantramangupta , cool :+1:. 

BTW @prashantramangupta , is there any way to exclude from coverage autogenerated files like [control_service.pb.go](https://coveralls.io/builds/24196917/source?filename=escrow/control_service.pb.go) as they negatively affect coverage ratio?

**Comment by prashantramangupta** [comment]
Sure, will look into this. There must be some way to avoid autogenerated files.

**Pull request merged**
